FROM registry.access.redhat.com/ubi9/python-312

WORKDIR /code

COPY ./requirements.txt /code/requirements.txt

RUN pip install --upgrade pip && pip install --no-cache-dir --upgrade -r /code/requirements.txt

COPY ./app /code/app

EXPOSE 8081

ENV DATABASE_URL=postgresql+asyncpg://user_service:password@postgres/user_db

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8081"]