version: 3

services:
  postgres:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    volumes: 
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=s3cret
      - POSTGRES_DB=user_db
    networks:
      - user_service
  user-register:
    container_name: user-registration-app
    image: user-registration-app:latest
    build:
      context: .
      dockerfile: Containerfile
    depends_on:
      - postgres
    ports:
      - "8081:8081"
    environment:
      DATABASE_URL: postgresql://dbuser:s3cret@postgres:5432/user_db
    networks:
      - user_service
  #pgadmin:
  #  image: dpage/pgadmin4
  #  depends_on:
  #    - postgres
  #  ports:
  #    - "8081:80"
  #  environment:
  #    PGADMIN_DEFAULT_EMAIL: mail@example.com
  #    PGADMIN_DEFAULT_PASSWORD: s3cret
  #  networks:
  #    - monoapp
networks:
  user_service: {}
volumes:
  postgres_data: 
