apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm-app
  annotations:
    description: VM app
  labels:
    app: vm-app
    os.template.kubevirt.io/fedora: 'true'
  namespace: vm-apps
spec:
  running: true
  template:
    metadata:
      annotations:
        vm.kubevirt.io/flavor: small
        vm.kubevirt.io/os: fedora
        vm.kubevirt.io/workload: server
      labels:
        kubevirt.io/domain: vm-app
        kubevirt.io/size: small
        vm.kubevirt.io/name: vm-app
    spec:
      domain:
        cpu:
          cores: 1
          sockets: 1
          threads: 1
        devices:
          disks:
            - disk:
                bus: virtio
              name: rootdisk
            - disk:
                bus: virtio
              name: cloudinitdisk
          interfaces:
            - masquerade: {}
              model: virtio
              name: default
          networkInterfaceMultiqueue: true
          rng: {}
        features:
          acpi: {}
          smm:
            enabled: true
        firmware:
          bootloader:
            efi: {}
        machine:
          type: q35
        memory:
          guest: 2Gi
      hostname: vm-app
      networks:
        - name: default
          pod: {}
      terminationGracePeriodSeconds: 180
      volumes:
        - name: rootdisk
          containerDisk:
            image: quay.io/containerdisks/fedora
        - cloudInitNoCloud:
            userData: |-
              #cloud-config
              user: user1
              password: openshift
              chpasswd: { expire: False }
              packages:
                - git
              runcmd:
                - mkdir /home/user1
                - git clone https://github.com/nikolaus-lemberski/summit-2024-app-mod-lab.git /home/user1/app/
                - chown -R user1:user1 /home/user1/app/vm-app
                - cd /home/user1/app/vm-app
                - export PORT=5000
                - sh /home/user1/app/vm-app/start-on-vm.sh
          name: cloudinitdisk
